variables:
  PIPELINE_CONTAINER_NAME: 'node-${CI_PROJECT_NAME}-pipeline'

stages:
  - construct
  - deploy
  - destruct

construct-container:
  stage: construct
  script:
    - set -e
    # 构建node环境,创建工作目录
    - sudo docker run -itd --name ${PIPELINE_CONTAINER_NAME} -w /opt/web node
    # 复制文件到工作目录
    - sudo docker cp ./ ${PIPELINE_CONTAINER_NAME}:/opt/web/
    # 安装依赖
    - sudo docker exec -i ${PIPELINE_CONTAINER_NAME} npm install --registry https://registry.npm.taobao.org
    # 编译 【修改这边的编译条件】
    - sudo docker exec -i ${PIPELINE_CONTAINER_NAME} npm run build
  only:
    - master
  tags:
    - cocos-ssg-shutupandtakemymoney

deploy-container:
  stage: deploy
  script:
    #删除软链
    - sudo rm -rf /home/nhuser/devtools/data/nginx/portal-web
    - set -e
      #创建文件夹
    - sudo mkdir -p /home/nhuser/devtools/data/nginx/portal-web-backup/portal-web-${CI_PIPELINE_ID}
      #复制容器编译完成后的文件到目标物理机目录 【修改这边的/opt/web/dist目录】
    - sudo docker cp ${PIPELINE_CONTAINER_NAME}:/opt/web/build /home/nhuser/devtools/data/nginx/portal-web-backup/portal-web-${CI_PIPELINE_ID}
      #将目标物理机文件软链到web目录【修改这边的/dist目录】
    - sudo ln -s /home/nhuser/devtools/data/nginx/portal-web-backup/portal-web-${CI_PIPELINE_ID}/build /home/nhuser/devtools/data/nginx/portal-web
  only:
    - master
  tags:
    - cocos-ssg-shutupandtakemymoney

destruct-container:
  stage: destruct
  script:
    - set -e
    # 删除node环境
    - sudo docker stop ${PIPELINE_CONTAINER_NAME}
    - sudo docker rm ${PIPELINE_CONTAINER_NAME}
  only:
    - master
  tags:
    - cocos-ssg-shutupandtakemymoney
  when: always
